# Generated by Django 5.2 on 2025-05-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='Untitled Detail', max_length=255),
        ),
    ]
