# Generated by Django 5.2 on 2025-05-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offerdetail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='creator',
            new_name='user',
        ),
    ]
