# Generated by Django 5.2 on 2025-05-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_rename_price_offer_price_basic_offer_price_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='delivery_time',
            field=models.PositiveIntegerField(default=7, help_text='Lieferzeit in Tagen'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_basic',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
