# Generated by Django 5.2 on 2025-05-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offer_delivery_time_alter_offer_price_basic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price_basic',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price_premium',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price_standard',
        ),
    ]
