# Generated by Django 5.2 on 2025-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_offerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0, help_text='Number revisions the customer is allowed to request. -1 for unlimited revisions'),
        ),
    ]
