# Generated by Django 5.2 on 2025-05-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_offerdetail_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
