# Generated by Django 5.2 on 2025-05-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0007_offerdetail_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='offer_pics/'),
        ),
    ]
